// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScientificActivityDatabaseImplement;

#nullable disable

namespace ScientificActivityDatabaseImplement.Migrations
{
    [DbContext(typeof(ScientificActivityDatabase))]
    [Migration("20260430140244_AddELibraryProfileAndPublicationCategories")]
    partial class AddELibraryProfileAndPublicationCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Organizer")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectArea")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ConferenceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ConferenceId", "TagId")
                        .IsUnique();

                    b.ToTable("ConferenceTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ELibraryAuthorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("AverageCitationsPerPublication")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("AverageWeightedImpactFactorCited")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("AverageWeightedImpactFactorPublished")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("CitationsAllLast5YearsCount")
                        .HasColumnType("integer");

                    b.Property<string>("CitationsCoreRinc5YearsByEndYearJson")
                        .HasColumnType("text");

                    b.Property<string>("CitationsCoreRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("CitationsCoreRincCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CitationsCoreRincLast5YearsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CitationsCountElibrary")
                        .HasColumnType("integer");

                    b.Property<int?>("CitationsCountRinc")
                        .HasColumnType("integer");

                    b.Property<string>("CitationsRinc5YearsByEndYearJson")
                        .HasColumnType("text");

                    b.Property<string>("CitationsRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("CitationsRincLast5YearsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CitedPublicationsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CoauthorCitationsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CoauthorsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<int?>("FirstPublicationYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ForeignArticlesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ForeignJournalCitationsCount")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HIndexCoreRinc")
                        .HasColumnType("integer");

                    b.Property<string>("HIndexCoreRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("HIndexElibrary")
                        .HasColumnType("integer");

                    b.Property<int?>("HIndexRinc")
                        .HasColumnType("integer");

                    b.Property<string>("HIndexRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("HIndexWithoutSelfCitations")
                        .HasColumnType("integer");

                    b.Property<int?>("ImpactFactorArticlesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ImpactFactorJournalCitationsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainRubricGrnti")
                        .HasColumnType("text");

                    b.Property<string>("MainRubricOecd")
                        .HasColumnType("text");

                    b.Property<int?>("MostCitedPublicationCitationsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<int?>("PercentileCoreRinc")
                        .HasColumnType("integer");

                    b.Property<string>("PercentileCoreRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("PublicationsCitingAuthorCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationsCoreRinc5YearsByEndYearJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicationsCoreRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("PublicationsCoreRincCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicationsCoreRincLast5YearsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicationsCountElibrary")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicationsCountRinc")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationsRinc5YearsByEndYearJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicationsRincByYearJson")
                        .HasColumnType("text");

                    b.Property<int?>("PublicationsRincLast5YearsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResearchTopics")
                        .HasColumnType("text");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("integer");

                    b.Property<int?>("RussianArticlesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RussianJournalCitationsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SelfCitationsCount")
                        .HasColumnType("integer");

                    b.Property<string>("SpinCode")
                        .HasColumnType("text");

                    b.Property<int?>("VakArticlesCount")
                        .HasColumnType("integer");

                    b.Property<int?>("VakJournalCitationsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ResearcherId")
                        .IsUnique();

                    b.ToTable("ELibraryAuthorProfiles");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ContestNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectArea")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.GrantTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrantId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("GrantId", "TagId")
                        .IsUnique();

                    b.ToTable("GrantTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("EIssn")
                        .HasColumnType("text");

                    b.Property<bool>("IsVak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhiteList")
                        .HasColumnType("boolean");

                    b.Property<string>("Issn")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<int?>("RcsiRecordSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectArea")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WhiteListAcceptedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WhiteListDiscontinuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WhiteListLevel2023")
                        .HasColumnType("integer");

                    b.Property<int?>("WhiteListLevel2025")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteListNotice")
                        .HasColumnType("text");

                    b.Property<string>("WhiteListState")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Issn");

                    b.HasIndex("RcsiRecordSourceId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.JournalTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JournalId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("JournalId", "TagId")
                        .IsUnique();

                    b.ToTable("JournalTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.JournalVakSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JournalId")
                        .HasColumnType("integer");

                    b.Property<string>("ScienceBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialtyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JournalId", "SpecialtyCode", "ScienceBranch", "DateFrom", "DateTo")
                        .IsUnique();

                    b.ToTable("JournalVakSpecialties");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CitationsRincCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ConferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("Doi")
                        .HasColumnType("text");

                    b.Property<string>("ELibraryId")
                        .HasColumnType("text");

                    b.Property<bool>("IsInCoreRinc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRinc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRsci")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopusQ1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopusQ2")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopusQ3")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopusQ4")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVakCategory1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVakCategory2")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVakCategory3")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebOfScienceNoQuartile")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebOfScienceQ1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebOfScienceQ2")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebOfScienceQ3")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebOfScienceQ4")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhiteListLevel1")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhiteListLevel2")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhiteListLevel3")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhiteListLevel4")
                        .HasColumnType("boolean");

                    b.Property<int?>("JournalId")
                        .HasColumnType("integer");

                    b.Property<string>("Keywords")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("integer");

                    b.Property<string>("RubricAsjc")
                        .HasColumnType("text");

                    b.Property<string>("RubricGrnti")
                        .HasColumnType("text");

                    b.Property<string>("RubricOecd")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("VakSpecialty")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("ELibraryId");

                    b.HasIndex("JournalId");

                    b.HasIndex("ResearcherId", "ELibraryId")
                        .IsUnique();

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Researcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicDegree")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ELibraryAuthorId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearchTopics")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Researchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicDegree = 0,
                            Department = "Администрация",
                            Email = "admin@science.local",
                            FirstName = "Системы",
                            IsActive = true,
                            LastName = "Администратор",
                            PasswordHash = "admin",
                            Phone = "79990000000",
                            Position = "Администратор системы",
                            ResearchTopics = "Администрирование системы",
                            Role = 2
                        });
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ResearcherInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ResearcherId");

                    b.ToTable("ResearcherInterests");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ResearcherTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResearcherId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ResearcherId", "TagId")
                        .IsUnique();

                    b.ToTable("ResearcherTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ConferenceTag", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Conference", "Conference")
                        .WithMany("ConferenceTags")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Tag", "Tag")
                        .WithMany("ConferenceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ELibraryAuthorProfile", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Researcher", "Researcher")
                        .WithOne()
                        .HasForeignKey("ScientificActivityDatabaseImplement.Models.ELibraryAuthorProfile", "ResearcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Researcher");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.GrantTag", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Grant", "Grant")
                        .WithMany("GrantTags")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Tag", "Tag")
                        .WithMany("GrantTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.JournalTag", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Journal", "Journal")
                        .WithMany("JournalTags")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Tag", "Tag")
                        .WithMany("JournalTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.JournalVakSpecialty", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Journal", "Journal")
                        .WithMany("VakSpecialties")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Publication", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Conference", "Conference")
                        .WithMany("Publications")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Journal", "Journal")
                        .WithMany("Publications")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Researcher", "Researcher")
                        .WithMany("Publications")
                        .HasForeignKey("ResearcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("Journal");

                    b.Navigation("Researcher");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ResearcherInterest", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Researcher", "Researcher")
                        .WithMany("Interests")
                        .HasForeignKey("ResearcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Researcher");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.ResearcherTag", b =>
                {
                    b.HasOne("ScientificActivityDatabaseImplement.Models.Researcher", "Researcher")
                        .WithMany("ResearcherTags")
                        .HasForeignKey("ResearcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificActivityDatabaseImplement.Models.Tag", "Tag")
                        .WithMany("ResearcherTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Researcher");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Conference", b =>
                {
                    b.Navigation("ConferenceTags");

                    b.Navigation("Publications");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Grant", b =>
                {
                    b.Navigation("GrantTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Journal", b =>
                {
                    b.Navigation("JournalTags");

                    b.Navigation("Publications");

                    b.Navigation("VakSpecialties");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Researcher", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Publications");

                    b.Navigation("ResearcherTags");
                });

            modelBuilder.Entity("ScientificActivityDatabaseImplement.Models.Tag", b =>
                {
                    b.Navigation("ConferenceTags");

                    b.Navigation("GrantTags");

                    b.Navigation("JournalTags");

                    b.Navigation("ResearcherTags");
                });
#pragma warning restore 612, 618
        }
    }
}
